LouisMazel/maz-ui

packages/components/MazInputTags/_main.vue, packages/components/MazPhoneNumberInput/_main.vue, packages/components/MazPicker/_main.vue, packages/components/MazSearch/_main.vue, packages/components/MazSelect/_main.vue, packages/scss/components/maz-input-tags.scss, packages/scss/components/maz-select.scss, packages/scss/style-helpers/animation.scss, src/views/Documentation/views/components/MazPickerDoc/index.vue, src/views/Documentation/views/components/MazSelectDoc/index.vue
- Allow left & right icon slots of MazInputs parents (MazSelect, MazSearch, MazPicker, MazPhoneNumberInput)
- **[MazSelect]** Add `multiple` options to choose multiple values
=> [Release 1.1.4]

packages/components/MazDialog/_main.vue, packages/components/MazPicker/PickersContainer/Calendar/MonthPicker/README.md, packages/components/MazPicker/PickersContainer/Calendar/MonthPicker/index.vue, packages/components/MazPicker/PickersContainer/Calendar/index.vue, packages/components/MazPicker/PickersContainer/FooterPicker/README.md, packages/components/MazPicker/PickersContainer/FooterPicker/index.vue, packages/components/MazPicker/PickersContainer/index.vue, packages/components/MazPicker/utils.js
- **[MazInput]**: Apply the good border color when input is focused and has state error, warning or valid
- **[MazPicker]**: Make valid button disabled when value is not picked
- **[MazDialog]**: Add keyboard listener to allow close dialog with escape key
=> [release-1.2.7]

documentation/pages/documentation/maz-phone-number-input/index.vue, packages/components/MazPhoneNumberInput/_main.vue
- **[MazPhoneNumberInput]**: Improved reactivity - Now the phone number input UI is updated when you update the value
=> [MazPhoneNumberInput] Improved reactivity

documentation/layouts/documentation.vue, documentation/pages/documentation/maz-btn/index.vue, documentation/pages/documentation/maz-input/index.vue, packages/components/MazBtn/README.md, packages/components/MazBtn/_main.vue, packages/scss/components/common/_maz-input.scss, packages/scss/components/maz-input-tags.scss, packages/scss/components/maz-progress-bar.scss, packages/scss/style-helpers/btn.scss
- **[[MazBtn]](https://louismazel.github.io/maz-ui/documentation/maz-btn)**: Add the `xl` size
- **[MazInput][MazInputTags][MazBtn]**: Use relative font size to fit the components
=> release-1.2.11

documentation/assets/scss/main.scss, documentation/components/ComponentContainer/index.vue, documentation/components/NavHeader/index.vue, documentation/constantes/index.js, documentation/layouts/documentation.vue, documentation/pages/documentation/colors/index.vue, documentation/pages/documentation/maz-sidebar/index.vue, packages/components/MazBtn/_main.vue, packages/components/MazDialog/_main.vue, packages/components/MazSidebar/_main.vue, packages/scss/components/common/_maz-btn.scss, packages/scss/components/maz-sidebar.scss
* [MazDialog] Disallow click outside listener when fullsize mode is enable
* [MazSidebar] Add `mini` & `expand-on-hover` options
* [MazBtn] Add `justify-start` option (when button have icon to separate text and icons)
=> [release-1.2.14]

documentation/components/LeftSidebarContent/index.vue, documentation/components/ProjectPreview/_subs/ProjectPreviewFooter.vue, documentation/components/SocialButtons/index.vue, documentation/pages/documentation/maz-btn/index.vue, package-lock.json, packages/components/MazBtn/_main.vue, packages/components/MazPhoneNumberInput/_main.vue, packages/scss/style-helpers/btn.scss, packages/scss/style-helpers/component_base.scss, packages/scss/style-helpers/flex.scss
- [MazPhoneNumberInput] Add ability to set set placeholder
- [MazPhoneNumberInput] Remove flag when noCountrySelector option is enable
- [MazBtn] Refactor text color & icons spacing
- Fix vulnerabilities
=> [release-v1.2.15]

packages/components/MazPhoneNumberInput/_main.vue, packages/components/MazPicker/PickersContainer/Calendar/TimePicker/index.vue
- **[MazPicker]** Remove debug code
- **[MazPhoneNumberInput]** Don't emit if no value
=> [release-v1.4.6]

documentation/pages/documentation/maz-input/index.vue, packages/components/MazInput/README.md, packages/components/MazInput/_main.vue
- **[maz-input]** add option to add a debounce before emit value
=> [release-v1.5.2] feat(maz-input): add option to add a debounce (500ms) before emit value

documentation/nuxt.config.js, documentation/pages/documentation/maz-slider/index.vue, packages/components/MazSlider/_main.vue, packages/scss/components/maz-slider.scss
- **[maz-slider]** add option to disables cursor animation
=> [release-v1.5.3] feat(maz-slider): add option to disables cursor animation

documentation/pages/documentation/maz-btn-group/index.vue, documentation/pages/documentation/maz-btn/index.vue, documentation/pages/documentation/maz-select/index.vue, packages/components/MazBtn/_main.vue, packages/components/MazBtnGroup/_main.vue, packages/components/MazInput/_main.vue, packages/components/MazInputTags/_main.vue, packages/components/MazPhoneNumberInput/_main.vue, packages/components/MazSelect/_main.vue, packages/scss/components/common/_maz-btn.scss, packages/scss/components/common/_maz-input.scss, packages/scss/components/common/_maz-select.scss, packages/scss/components/maz-input-tags.scss, packages/scss/components/maz-phone-number-input.scss, packages/scss/style-helpers/btn.scss, packages/scss/style-helpers/variables/_colors.scss
- **[maz-btn-group]** add support of icons
- **[maz-btn]** add support icons for normal button
- **[maz-select]** option list has font-size according with input size
- **[maz-input]** label position according with input size
- **[CSS-colors]** change light color to #EEE
=> [release-v1.5.8]

packages/components/MazSelect/_main.vue
If yes, please describe the impact and migration path for existing applications:
**The PR fulfills these requirements:**
If adding a **new feature**, the PR's description includes:
**Other information:**
=> [MazPhoneNumberInput] allow search by country code

packages/components/MazPhoneNumberInput/_main.vue
- https://github.com/LouisMazel/maz-ui/issues/196
=> refactor(lib): MazPhoneNumberInput V2 - keep cursor position while editing

packages/docs/package-lock.json, packages/lib/package/components/MazInput.vue, packages/lib/package/components/MazPhoneNumberInput.vue, packages/testing/src/App.vue
- https://github.com/LouisMazel/maz-ui/issues/196
=> refactor(lib): MazPhoneNumberInput - keep cursor position while editing

CHANGELOG.md, lerna.json, packages/docs/CHANGELOG.md, packages/docs/package-lock.json, packages/docs/package.json, packages/lib/CHANGELOG.md, packages/lib/package-lock.json, packages/lib/package.json, packages/lib/package/components/MazBackDrop.vue, packages/lib/package/components/MazDrawer.vue, packages/testing/CHANGELOG.md, packages/testing/package-lock.json, packages/testing/package.json
=> Release/3.0.0 next.5

packages/lib/package-lock.json, packages/lib/package/components/MazInput.vue, packages/testing/src/App.vue
=> feat(lib): MazInput - adding style color for autofill

CHANGELOG.md, lerna.json, packages/docs/CHANGELOG.md, packages/docs/package-lock.json, packages/docs/package.json, packages/lib/CHANGELOG.md, packages/lib/package-lock.json, packages/lib/package.json, packages/lib/package/components/MazInput.vue, packages/testing/CHANGELOG.md, packages/testing/package-lock.json, packages/testing/package.json, packages/testing/src/App.vue
=> Release/3.0.0 next.8

packages/docs/docs/.vuepress/clientAppEnhance.ts
=> fix(docs): aos installation on client side

packages/docs/docs/plugins/aos.md
=> fix(docs): aos implementation

packages/docs/docs/components/maz-input-tags.md
=> refactor(docs): MazInputTags - improve doc

packages/docs/docs/components/maz-input.md
=> refactor(docs): MazInput - improve doc

packages/lib/Makefile
=> refactor(lib): publish script

packages/lib/package/components/MazPicker.vue, packages/lib/package/components/MazPicker/MazPickerCalendar.vue, packages/lib/package/components/MazPicker/MazPickerCalendarMonth/MazPickerCalendarGrid.vue, packages/lib/package/components/MazPicker/MazPickerCalendarMonth/MazPickerCalendarMonth.vue, packages/lib/package/components/MazPicker/MazPickerContainer.vue, packages/lib/package/components/MazPicker/MazPickerShortcuts.vue, packages/lib/package/components/MazPicker/MazPickerTime.vue, packages/lib/tests/specs/components/__snapshots__/maz-picker.spec.ts.snap
=> feat(lib): maz-picker - add disabled prop option

packages/lib/package/components/MazCheckbox.vue
=> feat(lib): maz-checkbox - use id or create id by instance

packages/docs/package-lock.json, packages/docs/package.json
=> refactor(docs): use maz-ui 3.0.2

packages/lib/package/components/MazPicker.vue, packages/lib/tests/specs/components/__snapshots__/maz-checkbox.spec.ts.snap, packages/lib/tests/specs/components/__snapshots__/maz-picker.spec.ts.snap
----
This PR will fix the issue reported in #348 
Thanks @emg36
=> fix(lib): maz-picker - 12 hour format on time picker mode

CHANGELOG.md, lerna.json, packages/docs/CHANGELOG.md, packages/docs/package-lock.json, packages/docs/package.json, packages/lib/CHANGELOG.md, packages/lib/package-lock.json, packages/lib/package.json, packages/lib/package/components/MazPicker.vue, packages/lib/tests/specs/components/__snapshots__/maz-checkbox.spec.ts.snap, packages/lib/tests/specs/components/__snapshots__/maz-picker.spec.ts.snap, packages/lib/tests/specs/components/maz-checkbox.spec.ts, packages/lib/tests/specs/components/maz-picker.spec.ts, packages/testing/CHANGELOG.md, packages/testing/package-lock.json, packages/testing/package.json
* fix(lib): maz-picker - 12 hour format on time picker mode
=> release(3.0.3): maz-picker - 12 hour format on time picker mode

.github/workflows/doc-build-test.yml, .github/workflows/doc-deploy.yml, packages/docs/package-lock.json, packages/docs/package.json
=> fix(docs): build error

CHANGELOG.md, Makefile, lerna.json, packages/docs/CHANGELOG.md, packages/docs/package-lock.json, packages/docs/package.json, packages/lib/CHANGELOG.md, packages/lib/package-lock.json, packages/lib/package.json, packages/lib/package/components/MazPicker.vue, packages/lib/package/components/MazPicker/MazPickerCalendar.vue, packages/lib/package/components/MazPicker/MazPickerCalendarMonth/MazPickerCalendarGrid.vue, packages/lib/package/components/MazPicker/MazPickerHeader.vue, packages/testing/CHANGELOG.md, packages/testing/package-lock.json, packages/testing/package.json
----
- fix(lib): maz-picker - JS error when the model value is null #359
=> release: 3.0.6

.github/workflows/doc-build-test.yml, .github/workflows/doc-deploy.yml, packages/docs/docs/.vuepress/config.ts, packages/docs/docs/.vuepress/configs/components.ts, packages/docs/docs/components/maz-select.md, packages/docs/docs/components/maz-stepper.md, packages/docs/package-lock.json, packages/docs/package.json, packages/lib/package-lock.json, packages/lib/package/components/MazSelect.vue, packages/lib/package/components/MazSlider.vue, packages/lib/package/components/MazStepper.vue, packages/lib/package/components/MazTransitionExpand.vue, packages/lib/package/components/index.ts, packages/lib/tests/specs/components/__snapshots__/maz-select.spec.ts.snap, packages/lib/tests/specs/components/__snapshots__/maz-slider.spec.ts.snap, packages/lib/tests/specs/components/__snapshots__/maz-stepper.spec.ts.snap, packages/lib/tests/specs/components/__snapshots__/maz-transition-expand.spec.ts.snap, packages/lib/tests/specs/components/maz-slider.spec.ts, packages/lib/tests/specs/components/maz-stepper.spec.ts, packages/lib/tests/specs/components/maz-transition-expand.spec.ts, packages/testing/package-lock.json
- feature: new  component - maz-stepper
- fix: maz-slider - cursor border color
- fix: maz-select - required attribute
=> feat(lib): new component - maz-stepper

.github/workflows/doc-build-test.yml, .github/workflows/doc-deploy.yml, packages/docs/docs/.vuepress/client.ts, packages/docs/docs/.vuepress/config.ts, packages/docs/docs/components/maz-icon.md, packages/docs/docs/helpers/idle-timeout.md, packages/docs/docs/helpers/theme-handler.md, packages/docs/docs/helpers/user-visibility.md, packages/docs/package-lock.json, packages/docs/package.json
=> fix(docs): doc build error - use maz-ui from npm

packages/lib/.eslintrc.js, packages/lib/package/components/MazInput.vue, packages/lib/package/components/MazPhoneNumberInput.vue, packages/lib/package/components/MazPhoneNumberInput/constantes/locales.ts, packages/lib/package/components/MazSelect.vue, packages/lib/tests/specs/components/__snapshots__/maz-select.spec.ts.snap
- **MazSelect** - Add input to search in options list - https://github.com/LouisMazel/maz-ui/commit/3ddc99cfcd963609863b0a65a8f331f24582dfb9
- #363 
- #191
=> feat(lib): maz-select - add searching option

package-lock.json, package.json
=> chore(root): update deps

.github/PULL_REQUEST_TEMPLATE.md, packages/docs/docs/.vuepress/config.ts, packages/docs/docs/.vuepress/styles/index.scss, packages/docs/docs/components/maz-select.md, packages/docs/package-lock.json, packages/docs/package.json
=> docs: maz-select

.cz-config.js, .husky/pre-commit, .prettierignore, Makefile, lerna.json, package-lock.json, package.json, packages/docs/Makefile, packages/docs/package.json, packages/lib/Makefile, packages/lib/package-lock.json, packages/lib/package.json, packages/testing/Makefile, packages/testing/package-lock.json, packages/testing/package.json, scripts/lightweight-tags-to-annotated.sh
=> chore: update deps & scripts in makefile

packages/lib/Makefile, packages/lib/build/build-components-entry.js, packages/lib/build/build-entries.js, packages/lib/build/compile-scss.js, packages/lib/build/copy-components-types.js, packages/lib/build/generate-components-entry.js, packages/lib/build/get-component-list.js, packages/lib/build/rollup.config.js, packages/lib/build/rollup.types.config.js, packages/lib/package-lock.json, packages/lib/package.json
=> chore(lib): use sass instead of node-sass

lerna.json
=> chore: allow lerna only on master branch

.github/workflows/doc-build-test.yml, .github/workflows/doc-deploy.yml, .github/workflows/lib-publish.yml, .github/workflows/lib-test-build.yml, .github/workflows/lib-test-lint.yml, .github/workflows/lib-test-unit.yml
=> ci: ga update plugin versions

CHANGELOG.md, lerna.json, packages/docs/CHANGELOG.md, packages/docs/package-lock.json, packages/docs/package.json, packages/lib/.eslintrc.js, packages/lib/CHANGELOG.md, packages/lib/package-lock.json, packages/lib/package.json, packages/lib/package/components/MazPhoneNumberInput.vue, packages/lib/package/components/MazPhoneNumberInput/utils/index.ts, packages/lib/tests/specs/components/maz-phone-number-input.spec.ts, packages/testing/CHANGELOG.md, packages/testing/package-lock.json, packages/testing/package.json
=> release: v3.3.1

lerna.json, packages/lib/package/components/MazBackDrop.vue, packages/lib/package/components/MazInput.vue, packages/lib/package/components/MazSelect.vue, packages/lib/package/components/MazSlider.vue, packages/lib/tests/specs/components/__snapshots__/maz-input-price.spec.ts.snap, packages/lib/tests/specs/components/__snapshots__/maz-input.spec.ts.snap, packages/lib/tests/specs/components/__snapshots__/maz-phone-number-input.spec.ts.snap, packages/lib/tests/specs/components/__snapshots__/maz-picker.spec.ts.snap, packages/lib/tests/specs/components/__snapshots__/maz-select.spec.ts.snap, packages/testing/src/App.vue
- **MazSelect**: required option #372
--- 
=> fix(lib): maz select required prop

packages/docs/package.json
=> chore(docs): upgrade maz-ui version to 3.3.2

packages/docs/docs/components/maz-stepper.md, packages/docs/package-lock.json, packages/lib/.vscode/settings.json, packages/lib/package/components/MazPicker/MazPickerCalendarMonth/MazPickerCalendarGrid.vue, packages/lib/package/components/MazStepper.vue, packages/lib/stylelint.config.js, packages/lib/tests/specs/components/__snapshots__/maz-stepper.spec.ts.snap, packages/testing/stylelint.config.js
=> feat(lib): maz-stepper colors & validated steps UI

CHANGELOG.md, lerna.json, packages/docs/docs/components/maz-stepper.md, packages/docs/package-lock.json, packages/lib/.vscode/settings.json, packages/lib/CHANGELOG.md, packages/lib/package-lock.json, packages/lib/package.json, packages/lib/package/components/MazPicker/MazPickerCalendarMonth/MazPickerCalendarGrid.vue, packages/lib/package/components/MazStepper.vue, packages/lib/stylelint.config.js, packages/lib/tests/specs/components/__snapshots__/maz-stepper.spec.ts.snap, packages/testing/stylelint.config.js
=> feat(lib): maz-stepper colors & validated steps UI (#431)

packages/docs/docs/guide/getting-started.md, packages/docs/package-lock.json, packages/lib/package-lock.json
=> docs: nuxt tag version

.codeclimate.yml, .github/workflows/lib-test-unit.yml, packages/lib/package.json, packages/lib/package/tailwindcss/tailwind.config.js, packages/lib/package/tailwindcss/utils/colors.js, packages/lib/package/tailwindcss/variables/breakpoints.js, packages/lib/package/tailwindcss/variables/utilities.js, packages/lib/package/tailwindcss/variables/z-indexes.js, packages/lib/tailwind.config.js
=> refactor(lib): exclude classes from style for tailwind compiling

.versionrc.js, packages/lib/package/components/MazSelect.vue, packages/lib/package/css/maz-ui-vars.css
=> fix(lib): danger color & maz-select

packages/docs/docs/components/maz-select.md
If yes, please describe the impact and migration path for existing applications:
**The PR fulfills these requirements:**
If adding a **new feature**, the PR's description includes:
**Other information:**
=> fix(docs): MazSelect missing importation & typo

lerna.json, packages/docs/docs/components/maz-lazy-img.md, packages/lib/.eslintrc.js, packages/lib/package-lock.json, packages/lib/package.json, packages/lib/package/components/MazBackdrop.vue, packages/lib/package/components/MazChart.vue, packages/lib/package/components/MazChart/includes.ts, packages/lib/tests/helpers/document-event.ts, packages/lib/tests/specs/components/__snapshots__/maz-backdrop.spec.ts.snap, packages/lib/tests/specs/components/__snapshots__/maz-chart.spec.ts.snap, packages/lib/tests/specs/components/maz-backdrop.spec.ts, packages/lib/tests/specs/components/maz-btn.spec.ts, packages/lib/tests/specs/components/maz-chart.spec.ts, packages/lib/tests/specs/components/maz-icon.spec.ts, packages/lib/tests/specs/components/n-gallery.spec_temporary.ts.ts, packages/lib/vitest.config.ts, packages/lib/vitest.setup.ts
=> feat(docs): add doc for maz-lazy-img

packages/lib/package/components/MazDialogPromise.vue
=> fix(lib): maz-dialog-promise - bind right methods

packages/docs/docs/components/maz-phone-number-input.md
If yes, please describe the impact and migration path for existing applications:
**The PR fulfills these requirements:**
If adding a **new feature**, the PR's description includes:
**Other information:**
=> docs(docs): fix code closing tag issue

packages/docs/docs/components/maz-phone-number-input.md
=> refactor(docs): maz-phone-number-input - add documentation about search placeholder translation

package.json, packages/docs/docs/guide/nuxt.md, pnpm-lock.yaml
=> chore(root): upgrade dependencies

packages/lib/.gitignore, packages/lib/build/vite.config.ts, packages/lib/modules/types/shims-vue.d.ts, packages/lib/modules/types/svg.d.ts, packages/lib/package.json
=> fix(lib): building process

package.json, packages/lib/package.json, pnpm-lock.yaml
=> chore: upgrade dependencies

packages/docs/docs/composables/use-aos.md
Spotted this little typo
---
If yes, please describe the impact and migration path for existing applications:
**The PR fulfills these requirements:**
If adding a **new feature**, the PR's description includes:
**Other information:**
=> docs: fix typo in use-aos.md

packages/lib/build/vite.config.ts, packages/lib/tailwind.config.ts
=> refactor(lib): remove css injection by components

package.json, packages/maz-cli/package.json, packages/nuxt-module/package.json, packages/playground/package.json, pnpm-lock.yaml
=> chore: update dependencies

packages/lib/modules/plugins/toaster/toaster-handler.ts, packages/lib/modules/plugins/toaster/types.ts
=> fix(lib): toaster - add link and action to toaster options declaration type

packages/docs/docs/components/maz-picker.md, packages/lib/components/MazPicker/MazPickerCalendar.vue, packages/lib/components/MazPicker/MazPickerCalendarMonth/MazPickerCalendarDays.vue, packages/lib/components/MazPicker/MazPickerCalendarMonth/MazPickerCalendarGrid.vue, packages/lib/components/MazPicker/MazPickerCalendarMonth/MazPickerCalendarMonth.vue, packages/lib/components/MazPicker/utils.ts
- https://github.com/LouisMazel/maz-ui/issues/572
=> fix(lib): MazPicker - first day of week trouble

package.json, packages/docs/package.json, packages/lib/package.json, pnpm-lock.yaml
=> chore: upgrade deps

packages/docs/docs/.vitepress/theme/main.css, packages/docs/docs/components/maz-phone-number-input.md, packages/lib/components/MazPhoneNumberInput.vue
=> refactor(maz-ui): MazPhoneNumberInput - add slots to replace flags

packages/docs/docs/components/maz-gallery.md, packages/lib/components/MazGallery.vue, packages/lib/tests/specs/components/maz-gallery.spec.ts
=> refactor(maz-ui): MazGallery - add option to choose color of borders between images

packages/docs/docs/guide/getting-started.md, packages/docs/docs/plugins/aos.md
=> refactor(docs): use css package exports

packages/nuxt-module/src/module.ts, packages/nuxt-module/src/runtime/composables/use-aos.ts, packages/nuxt-module/src/runtime/composables/use-toast.ts, packages/nuxt-module/src/runtime/composables/use-wait.ts, packages/nuxt-module/src/runtime/plugins/aos.ts, packages/nuxt-module/src/runtime/plugins/maz-icon-path.ts, packages/nuxt-module/src/runtime/plugins/toaster.ts, packages/nuxt-module/src/runtime/plugins/wait.ts
=> refactor(nuxt-module): improve composables to support server side

CHANGELOG.md, packages/docs/docs/components/maz-transition-expand.md, packages/lib/components/MazChart.vue, packages/lib/components/MazTransitionExpand.vue
=> fix(maz-ui): MazTransition - do not apply animate duration to all childs

packages/nuxt-module/package.json
=> chore(nuxt-module): specify build cmd

packages/lib/tailwindcss/utils/colors.ts
=> fix(maz-ui): typing in tailwind utils

.github/workflows/builds.yml, packages/lib/package.json
=> chore(maz-ui): enable type checking before build

packages/docs/docs/components/maz-select.md, packages/lib/components/MazSelect.vue
=> style(maz-ui): MazSelect - improve list UI

packages/docs/docs/components/maz-table.md, packages/lib/components/MazTable.vue
=> refactor(maz-ui): MazTable - add possibility to add title in header

packages/lib/components/MazPhoneNumberInput.vue
=> fix(maz-ui): MazPhoneNumberInput - use the country code provided to initialize the component

.github/workflows/lib-test-unit-pr.yml
=> ci: fix test units with dependabot

packages/docs/docs/components/maz-select.md, packages/lib/components/MazSelect.vue, packages/lib/tests/specs/components/maz-select.spec.ts
- https://github.com/LouisMazel/maz-ui/discussions/773
=> feat(maz-ui): MazSelect - add optgroup

packages/docs/docs/components/maz-tabs.md, packages/lib/components/MazBadge.vue, packages/lib/components/MazTabsBar.vue, packages/playground/src/pages/index.vue
=> refactor(maz-ui): MazTabsBar - improve animations

package.json, packages/cli/.eslintrc.cjs, packages/docs/docs/.vitepress/config.mts, packages/docs/package.json, packages/maz-cli/src/commands/generate-css-variables/index.ts, packages/maz-cli/src/utils/logger.ts, pnpm-lock.yaml
=> chore(deps): use plugin of typescript-eslint instead of standard-with-typescript

package.json, packages/lib/package.json, pnpm-lock.yaml
=> chore(deps): upgrade dependencies

packages/docs/docs/.vitepress/theme/components/ComponentDemo.vue, packages/docs/docs/components/maz-phone-number-input.md, packages/lib/components/MazPhoneNumberInput.vue, packages/lib/components/MazPhoneNumberInput/CountrySelector.vue, packages/lib/components/MazPhoneNumberInput/PhoneInput.vue
=> refactor(maz-ui): MazPhoneNumberInput - improve responsive and add orientation prop option to choose the input orientation

packages/lib/components/MazPhoneNumberInput.vue, packages/lib/components/MazPhoneNumberInput/CountrySelector.vue, packages/lib/components/MazPhoneNumberInput/PhoneInput.vue, packages/lib/components/MazPhoneNumberInput/use-libphonenumber.ts, packages/lib/components/MazPhoneNumberInput/use-maz-phone-number-input.ts, packages/lib/tests/specs/components/MazPhoneNumberInput/use-libphonenumber.spec.ts, packages/lib/tests/specs/components/MazPhoneNumberInput/use-maz-phone-number-input.spec.ts, packages/lib/tests/specs/components/maz-phone-number-input.spec.ts, packages/playground/src/pages/index.vue
=> fix(maz-ui): MazPhoneNumberInput - use provide/inject for data to not sharing state between instances - issue #1024

packages/docs/docs/components/maz-btn.md, packages/docs/docs/components/maz-tabs.md, packages/lib/components/MazAvatar.vue, packages/lib/components/MazBadge.vue, packages/lib/components/MazBtn.vue, packages/lib/components/MazInput.vue
=> feat(maz-ui): MazBtn - add prop option to choose the rounded size

packages/lib/package.json, pnpm-lock.yaml
=> chore(deps): remove eslint from maz-ui's dependencies

packages/lib/components/MazInputCode.vue
=> refactor(maz-ui): MazInputCode - keyboard accessibility - support ArrowLeft and ArrowRight to switch input

packages/lib/components/MazPhoneNumberInput.vue, packages/lib/components/MazPhoneNumberInput/PhoneInput.vue
=> refactor(maz-ui): MazPhoneNumberInput - Add possibility to choose between label or placeholder for phone number input

packages/docs/docs/composables/use-swipe.md, packages/lib/modules/composables/useSwipe.ts, packages/lib/modules/helpers/swipe-handler.ts, packages/lib/tests/specs/composables/useSwipe.spec.ts, packages/lib/tests/specs/helpers/swipe-handler.spec.ts
=> refactor(maz-ui): useSwipe - add documentation and SSR compatibility

packages/lib/modules/composables/useFormValidator/utils.ts, packages/lib/tests/specs/composables/useFormValidator/utils.spec.ts
=> test(maz-ui): useFormValidator - add tests

packages/docs/docs/.vitepress/theme/main.css, packages/docs/docs/components/maz-select.md, packages/lib/components/MazSelect.vue
=> feat(maz-ui): MazSelect - add search-threshold prop option to adjust search results

packages/lib/components/MazPhoneNumberInput.vue, packages/lib/components/MazPhoneNumberInput/CountrySelector.vue, packages/lib/components/MazPhoneNumberInput/PhoneInput.vue, packages/lib/components/MazSelect.vue
=> fix(maz-ui): MazPhoneNumberInput - auto-fill/autocomplete - control each input attributes (#1156)

lerna.json, package.json, packages/cli/package.json, packages/docs/docs/guide/nuxt.md, packages/docs/package.json, packages/lib/package.json, packages/maz-cli/package.json, packages/nuxt-module/package.json, packages/nuxt-module/src/module.ts
=> refactor(nuxt-module): add import prefix to avoid conflicts with other libs or existing modules

packages/lib/components/MazAnimatedCounter.vue, packages/lib/tests/specs/components/MazAnimatedCounter.spec.ts, packages/lib/tests/specs/components/maz-circular-progress-bar.spec.ts
=> refactor(maz-ui): MazAnimateCounter - make it SSR friendly

.github/workflows/builds.yml, .github/workflows/cli-publish.yml, .github/workflows/doc-deploy.yml, .github/workflows/lib-publish.yml, .github/workflows/lib-test-unit-dependabot.yml, .github/workflows/lib-test-unit.yml, .github/workflows/linters.yml, packages/lib/build/vite.config.ts
=> fix(maz-ui): add hash to css files to avoid overriding

packages/docs/docs/.vitepress/theme/components/Layout.vue, packages/docs/docs/.vitepress/theme/index.ts, packages/docs/docs/components/maz-checklist.md, packages/docs/docs/index.md, packages/lib/components/constantes.ts, packages/lib/components/types.ts, packages/lib/vitest.config.mts
=> fix(docs): Suspense and hydration issues

.github/workflows/build-and-typecheck.yml, .github/workflows/linters.yml, .github/workflows/test-unit-dependabot.yml, .github/workflows/test-unit.yml, apps/docs/.vitepress/config.mts, apps/docs/.vitepress/configs/navbar.mts, apps/docs/.vitepress/theme/components/Layout.vue, apps/docs/.vitepress/theme/index.ts, apps/docs/.vitepress/theme/main.css, apps/docs/src/guide/themes.md, apps/docs/src/index.md, packages/lib/src/components/MazAvatar.vue, packages/lib/src/components/MazBadge.vue, packages/lib/src/components/MazBtn.vue, packages/lib/src/components/MazFullscreenLoader.vue, packages/lib/src/components/MazLink.vue, packages/lib/src/components/MazReadingProgressBar.vue, packages/lib/src/components/MazSelectCountry.vue, packages/themes/src/composables/__tests__/useTheme.test.ts, packages/themes/src/composables/useTheme.ts, packages/themes/src/plugin.ts, packages/themes/src/presets/mazUi.ts, packages/themes/src/types/index.ts
About link and mention about the v3 documentation
=> refactor(docs): add link to v3 documentation

.github/workflows/test-unit.yml, .qlty/qlty.toml, apps/docs/.vitepress/configs/navbar.mts, apps/docs/package.json, apps/docs/src/demo/ColorPicker.vue, apps/docs/src/demo/DemoDashboardPage.vue, apps/docs/src/demo/ThemeEditorPage.vue, apps/docs/src/guide/themes.md, apps/docs/src/theme-editor.md, packages/lib/src/components/MazBtn.vue, packages/lib/src/components/MazRadioButtons.vue
Theme editor: https://maz-ui.com/theme-editor
=> feat: theme editor
